<?php

/**
 * PluginarMenuCMSSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarMenuCMSSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarMenuCMSSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarMenuCMSSlot');
    }
}