<?php

/**
 * PluginarMenuSecundarySlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarMenuSecundarySlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarMenuSecundarySlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarMenuSecundarySlot');
    }
}