<?php

/**
 * PluginarDiagramHasArWallMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDiagramHasArWallMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDiagramHasArWallMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDiagramHasArWallMessage');
    }
}