<?php

/**
 * PluginarLavernaFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginarLavernaFile extends BasearLavernaFile
{
    /**
     * devuelve un array para serializar JSON
     * @return array
     */
    public function getInfo()
    {
        return array('id' => $this->getGuid(),
                'type' => $this->getType(),
                'src' => $this->getSrc(),
                'w' => $this->getW(),
                'h' => $this->getH(),
                'created' => $this->getCreatedAt(),
                'updated' => $this->getUpdatedAt());

    }

}