<?php

/**
 * PluginarLavernaDocHasArWallMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarLavernaDocHasArWallMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarLavernaDocHasArWallMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarLavernaDocHasArWallMessage');
    }
}