<?php

/**
 * PluginarDiagramTrashTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDiagramTrashTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDiagramTrashTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDiagramTrash');
    }
    
     /**
     * 
     * @param int $profileId
     * @param int $docId
     * @return query
     */
    public function getQueryDocProfile( $docId, $profileId, $conn = false)
    {
        $query = Doctrine_Core::getTable('arDiagramTrash')
            ->createQuery('u')
            ->where('u.diagram_id = ? AND u.user_id = ?', array($docId, $profileId));

        if ($conn)
        {
           $query->setConnection($conn);  
        }
        
        return $query;
    }
    
    /**
     * 
     * @param int $profileId
     * @param int $docId
     * @return arLavernaDocTrash
     */
    public function getByDocProfile($docId, $profileId,$conn = false )
    {
        $query = Doctrine_Core::getTable('arDiagramTrash')
                  ->getQueryDocProfile($docId, $profileId,$conn);

        return $query->fetchOne();
    }
    /**
     * true si el documento esta en la papelera para un
     * perfil
     * 
     * @param type $docId
     * @param type $profileId
     * @return boolean:     
     */
    public static function hasDocProfile($docId, $profileId, $conn = false)
    {
     $q = Doctrine::getTable('arDiagramTrash')
             ->getQueryDocProfile($docId, $profileId, $conn)
             ->select('COUNT(u.id)');

     return ($q->execute(array(),  Doctrine_Core::HYDRATE_SINGLE_SCALAR) > 0);
    }
}