<?php

/**
 * PluginarDiagramFavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDiagramFavoriteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDiagramFavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDiagramFavorite');
    }
    
    /**
     * 
     * @param int $profileId
     * @param int $docId
     * @return query
     */
    public function getQueryDocProfile( $docId, $profileId, $conn = false)
    {
        $query = Doctrine_Core::getTable('arDiagramFavorite')
            ->createQuery('u')
            ->where('u.diagram_id = ? AND u.user_id = ?', array($docId, $profileId));

        if ($conn)
        {
           $query->setConnection($conn);  
        }
        
        return $query;
    }
    
    /**
     * 
     * @param int $profileId
     * @param int $docId
     * @return arLavernaDocTrash
     */
    public function getByDocProfile($docId, $profileId,$conn = false )
    {
        $query = Doctrine_Core::getTable('arDiagramFavorite')
                  ->getQueryDocProfile($docId, $profileId,$conn);

        return $query->fetchOne();
    }
    /**
     * true si el documento es favorito
     * 
     * @param type $docId
     * @param type $profileId
     * @return boolean:     
     */
    public static function hasDocProfile($docId, $profileId, $conn = false)
    {
     $q = Doctrine::getTable('arDiagramFavorite')
             ->getQueryDocProfile($docId, $profileId, $conn)
             ->select('COUNT(u.id)');
     /*
     echo $docId;
     echo $profileId;
     echo $q->getSqlQuery();
     exit();*/
     return ($q->execute(array(),  Doctrine_Core::HYDRATE_SINGLE_SCALAR) > 0);
    }
    
    
}