<?php

/**
 * PluginarGalleryResponsiveSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarGalleryResponsiveSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarGalleryResponsiveSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarGalleryResponsiveSlot');
    }
}