<?php

/**
 * PluginarSliderResponsiveSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarSliderResponsiveSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarSliderResponsiveSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarSliderResponsiveSlot');
    }
}