<?php

/**
 * PluginarLogoSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarLogoSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarLogoSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarLogoSlot');
    }
}