<?php

/**
 * PluginarLastSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarLastSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarLastSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarLastSlot');
    }
}