<?php

/**
 * PluginarBlogSliderSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarBlogSliderSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarBlogSliderSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarBlogSliderSlot');
    }
}