<?php

/**
 * PluginarImageResponsiveSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarImageResponsiveSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarImageResponsiveSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarImageResponsiveSlot');
    }
}