<?php

/**
 * PluginarEventSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarEventSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarEventSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarEventSlot');
    }
}