<?php

/**
 * PluginarBlogSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarBlogSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarBlogSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarBlogSlot');
    }
}