<?php

/**
 * PluginarSessionHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarSessionHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarSessionHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarSessionHistory');
    }
}