<?php

/**
 * PluginarChatTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarChatTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarChatTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarChatToken');
    }
}