<?php

/**
 * PluginarWallImageUpload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginarWallImageUpload extends BasearWallImageUpload
{
    
    /**
     * es una imagen valida
     * 
     * @return boolean
     */
    /*
    public function hasValid()
    {
        return true;   
    }*/

}