<?php

/**
 * PluginarDropFileChunkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDropFileChunkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDropFileChunkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDropFileChunk');
    }
    
    /**
     *
     * @param <int $drop_file_id> 
     * @param <int $pos>
     * 
     * @return <arDropFileChunk>
     */
    public static function getByDropIdAndPos($drop_file_id, $pos)
    {

        $q = Doctrine_Core::getTable('arDropFileChunk')
               ->createQuery('c')
               ->where('(c.drop_file_id = ?) AND (c.pos = ?)',  array($drop_file_id, $pos));
        
       
        return $q->fetchOne();
    }
    
    
    public static function getByDropId($drop_file_id)
    {

        $q = Doctrine_Core::getTable('arDropFileChunk')
               ->createQuery('c')
               ->where('(c.drop_file_id = ?)',  array($drop_file_id));
        
       
        return $q->execute();
    }
    
    
    public static function countById($drop_file_id)
    {
 
        $q = Doctrine_Core::getTable('arDropFileChunk')
               ->createQuery('c')
               ->where('c.drop_file_id = ?', $drop_file_id)
               ->select('COUNT(c.id) as id');
        
        return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    
    
}