<?php

/**
 * PluginarTagHasArWallMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarTagHasArWallMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarTagHasArWallMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarTagHasArWallMessage');
    }
    
    
}