<?php

/**
 * PluginarWallMessageHasBlogItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallMessageHasBlogItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallMessageHasBlogItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallMessageHasBlogItem');
    }
}