<?php

/**
 * PluginarDropFileChunkPreviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDropFileChunkPreviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDropFileChunkPreviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDropFileChunkPreview');
    }
    
    /**
     *
     * @param <int $drop_file_id> 
     * @param <int $pos>
     * 
     * @return <arDropFileChunk>
     */
    public static function getByDropIdAndPos($drop_file_id, $pos)
    {

        $q = Doctrine_Core::getTable('arDropFileChunkPreview')
               ->createQuery('c')
               ->where('(c.drop_file_preview_id = ?) AND (c.pos = ?)',  array($drop_file_id, $pos));
        
       
        return $q->fetchOne();
    }
    
    public static function getByDropIdStyleAndPos($drop_file_id, $size_style, $pos)
    {
        $q = Doctrine_Core::getTable('arDropFileChunkPreview')
               ->createQuery('c')
               ->leftJoin('c.DropFilePreview dfp')
               ->where('(dfp.drop_file_id = ?) AND (dfp.size_style LIKE ?) AND (c.pos = ?)',  array($drop_file_id, $size_style, $pos));
        
        //echo $q->getSqlQuery();
        //exit();
        
        return $q->fetchOne();
    }
    
    public static function getByDropId($drop_file_id)
    {

        $q = Doctrine_Core::getTable('arDropFileChunkPreview')
               ->createQuery('c')
               ->where('c.drop_file_preview_id = ?',  array($drop_file_id))
               ->orderBy('c.pos ASC')
               ->select('c.chunkData');
        
        
        return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        //return $q->execute();
        
    }
    
    public static function countById($drop_file_id)
    {
 
        $q = Doctrine_Core::getTable('arDropFileChunkPreview')
               ->createQuery('c')
               ->where('c.drop_file_preview_id = ?', $drop_file_id)
               ->select('COUNT(c.id) as id');
        
        return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    
}