<?php

/**
 * PluginarWallComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginarWallComment extends BasearWallComment
{
    /**
     * mira si puede borrar el comentario
     * 
     * @return <boolean>: true si puede borrar el comentario del wall 
     */
    public function canDelete()
    {
        
        $commentUser = $this->getUser();
                
        if (sfConfig::get('app_arquematics_encrypt', false))
        {
          return ($commentUser->getId() == $this->EncContent->getId());  
        }
        else
        {
          //yes bad ...
          $aUser = sfContext::getInstance()->getUser();
          
          return ($commentUser->getId() == $aUser->getId());  
        }
    }
    
   /**
   * devuelve el registro de la imagen del usuario
   * 
   * @return <arProfileUpload>
   */
  public function getImageUserProfile()
  {
     return Doctrine_Core::getTable('arProfileUpload')->retrieveByUserId($this->getUserId());
  }
  
  /**
   * devuelve una cadena con el comentario
   * que se ha encriptado para un usuario contreto
   * 
   * @param <authUser $authUser>
   * @return <String> 
   */
  public function getEncryptTxt($authUser)
  {
     $messageEnc = Doctrine_Core::getTable('arWallCommentEnc')
                        ->retrieveContentById($this->getId(), $authUser->getId());
  
     if ($messageEnc &&  is_object($messageEnc))
     {
         return $messageEnc->getContent();
     }
     else return '';
  }

}