<?php

/**
 * PluginarGmapsLocateEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarGmapsLocateEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarGmapsLocateEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarGmapsLocateEnc');
    }
    
    /**
    * 
    * @param int $locate_id:
    * @param int $userId:
    * 
    * @return arGmapsLocateEnc
    */
    public function retrieveContentById($locate_id, $userId )
    {
        $query = Doctrine_Core::getTable('arGmapsLocateEnc')
            ->createQuery('u')
            ->andWhere('u.locate_id  = ?', $locate_id)
            ->andWhere('u.user_id = ?', $userId);

        return $query->fetchOne();
    }
    
    /**
     * array de usuarios para los que se ha codificado una dirección
     * 
     * @param <int $locate_id>
     * @return <array>
     */
    public function retrieveUserById($locate_id)
    {
        $q = Doctrine_Core::getTable('arGmapsLocateEnc')
            ->createQuery('u')
            ->andWhere('u.locate_id  = ?', $locate_id)
            ->select('u.user_id as id');
        
        return $q->execute(array(),Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
}