<?php

/**
 * PluginarGmapsLocate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginarGmapsLocate extends BasearGmapsLocate
{
    /**
     * guarda una relacion con un profile
     * 
     * @param <int $profileId>
     */
    public function saveRelatedProfile($profileId)
    {
        $arUsersGmapsLocate = new arUsersGmapsLocate();
        
        $arUsersGmapsLocate->setProfileId($profileId);
        $arUsersGmapsLocate->setGmapsLocateId($this->getId());
        
        $arUsersGmapsLocate->save();
    }
    
    /**
   * devuelve una cadena con el contenido del 
   * encriptado
   * 
   * @param <authUser $authUser>
   * @return <String> 
   */
  public function getEncryptTxt($authUser)
  {
      
     $arGmapsLocateEnc = Doctrine_Core::getTable('arGmapsLocateEnc')
                        ->retrieveContentById($this->getId(), $authUser->getId());
  
     if ($arGmapsLocateEnc &&  is_object($arGmapsLocateEnc))
     {
         return $arGmapsLocateEnc->getContent();
     }
     else return '';
  }
    
    /**
     * es una localizacion valida
     * 
     * @return boolean
     */
  /*
    public function hasValid()
    {
        return true;   
    }*/
    /**
     * lista con las ids para las que ha sido
     * codificada la direccion
     * 
     * @return <array>
     */
    public function getUserEncodedIds()
    {
        return Doctrine_Core::getTable('arGmapsLocateEnc')
                ->retrieveUserById($this->getId());
    }
    
}