<?php

/**
 * PluginarWallCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallComment');
    }
}