<?php

/**
 * PluginarUsersGmapsLocateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarUsersGmapsLocateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarUsersGmapsLocateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarUsersGmapsLocate');
    }
    
    
    
}