<?php

/**
 * PluginarWallLinkEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallLinkEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallLinkEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallLinkEnc');
    }
}