<?php

/**
 * PluginarDropFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDropFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDropFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDropFile');
    }
    
    /**
     * devuelve los recursos por array de ids
     *
     * @param <array $ids> 
     * 
     * @return <array of arDropFile>
     */
    public static function getByIds($ids)
    {

        $q = Doctrine_Query::create()
            ->from('arDropFile f')
            ->whereIn('f.id',$ids);
       
        return $q->execute();
    }
    
    public static function getById($drop_file_id, $conn = false)
    {
        $q = Doctrine_Core::getTable('arDropFile')
               ->createQuery('c')
               ->where('c.id = ?',  array($drop_file_id));
        
       if ($conn)
       {
           $q->setConnection($conn);
       }
        
       return $q->fetchOne();
    }
    
    
    
    public static function getQueryUnassociatedAll($userId,  $conn = false)
    {
        $q = Doctrine::getTable('arDropFile')
             ->createQuery('f')
             ->leftJoin('f.EncContent enc')
             ->andWhere('f.wall_message_id IS NULL AND f.user_id = ?', array($userId))
             ->andWhere('enc.user_id = ?', $userId);  
       if ($conn)
       {
           $q->setConnection($conn);
       }
       
       return $q;
    }
    
    public static function getQueryUnassociated($userId, $ready = true, $conn = false)
    {
        $q = Doctrine::getTable('arDropFile')
             ->createQuery('f')
             ->leftJoin('f.EncContent enc')
             ->andWhere('f.wall_message_id IS NULL AND f.ready = ? AND f.user_id = ?', array($userId, $ready))
             ->andWhere('enc.user_id = ?', $userId);  
       if ($conn)
       {
           $q->setConnection($conn);
       }
       
       return $q;
    }
    
    public static function getUnassociatedAll($userId, $conn = false)
    {
        $q = Doctrine::getTable('arDropFile')
              ->getQueryUnassociatedAll($userId,  $conn); 
         
        //echo $q->getSqlQuery();
        
        return $q->execute();
    }
   
    /**
     * ficheros del usuario que aún no se han asociado a un mensaje
     *
     *  @param type $userId
     * @param type $conn
     */
    public static function getUnassociated($userId, $conn = false)
    {
        $q = Doctrine::getTable('arDropFile')
              ->getQueryUnassociated($userId, true, $conn); 
       
        //echo $q->getSqlQuery();
     
        return $q->execute();
    }
    
    
    
    public static function countUnassociated($userId, $conn = false)
    {
        $q = Doctrine::getTable('arDropFile')
              ->getQueryUnassociated($userId, true, $conn)
              ->select('count(*) as count');
        
        return ($q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR) > 0);
    } 
}