<?php

/**
 * PluginarWallUploadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallUploadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallUploadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallUpload');
    }
    
    /**
    * devuelve un registro por la id
    * 
    * @param <$id>
    * @return <arWallUpload>
    */
  public function retrieveById($id)
  {
    $query = Doctrine_Core::getTable('arWallUpload')
            ->createQuery('u')
      ->where('u.id = ?', $id);

    return $query->fetchOne();
  }
  
   /**
    * devuelve un registro por el nombre
    * 
    * @param <$id>
    * @return <arWallUpload>
    */
  public function retrieveByName($name)
  {
    $query = Doctrine_Core::getTable('arWallUpload')
            ->createQuery('u')
            ->where('u.file_name = ?', $name);

    return $query->fetchOne();
  }
  
  /**
   * 
   * @param int $userId
   * @param int $guiId
   * @return arWallUpload
   */
  public function retrieveByUserGuiId($userId, $guiId)
  {
    $query = Doctrine_Core::getTable('arWallUpload')
            ->createQuery('u')
      ->where('u.user_id = ?', $userId)
      ->addWhere('u.gui_id = ?', $guiId);

    return $query->fetchOne();
  }
  
   /**
     * devuelve los ficheros por array de ids
     *
     * @param <array $ids> 
     * 
     * @return <array>
     */
    public static function getByIds($ids)
    {

        $q = Doctrine_Query::create()
            ->from('arWallUpload d')
            ->whereIn('d.id',$ids);
        

        return $q->execute();
    }
    /**
     * ficheros descargados en un mensaje
     * 
     * @param <integer $id>
     * @return <array arWallUpload>
     */
    public static function getUploads($id)
    {

         $q = Doctrine_Query::create()
            ->from('arWallUpload u')
            ->where('u.wall_message_id = ?',$id)
            ->orderBy('u.name');
        
        return $q->execute();
    }
    
    
}