<?php

/**
 * PluginarDropFileEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarDropFileEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarDropFileEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarDropFileEnc');
    }
    
    public static function countByFileId($dropFileId, $userId, $conn = false)
    {
        $q = Doctrine_Core::getTable('arDropFileEnc')
               ->createQuery('c')
               ->where('c.drop_file_id = ? AND c.user_id = ?',  array($dropFileId,$userId))
               ->select('count(*) as count');
        
       if ($conn)
       {
           $q->setConnection($conn);
       }
       
       return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
}