<?php

/**
 * PluginarFriendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarFriendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarFriendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarFriend');
    }
    
    public static function getStatus($userProfileId, $acceptProfileId, $conn = false)
    {
        if ($conn)
        {
           $q = Doctrine::getTable('arFriend')
             ->setConnection($conn)
             ->createQuery('f')
             ->where('((f.profile_id = ?) OR (f.friend_id = ?)) AND ((f.profile_id = ?) OR (f.friend_id = ?))',array($userProfileId, $userProfileId, $acceptProfileId, $acceptProfileId));  
        }
        else
        {
          $q = Doctrine::getTable('arFriend')
             ->createQuery('f')
             ->where('((f.profile_id = ?) OR (f.friend_id = ?)) AND ((f.profile_id = ?) OR (f.friend_id = ?))',array($userProfileId, $userProfileId, $acceptProfileId, $acceptProfileId));    
        }
        
         
         return $q->fetchOne();      
    }
    /**
     * estado en el que esta un usuario
     * 
     * @param <int $userProfileId>
     * @param <int $acceptProfileId>
     * @param <conn $conn>
     * 
     * @return <boolean>
     */
    public static function hasStatus($userProfileId, $acceptProfileId, $conn = false)
    {
       if ($conn)
       {
          $q = Doctrine::getTable('arFriend')
             ->setConnection($conn)
             ->createQuery('f')
            ->where('((f.profile_id = ?) OR (f.friend_id = ?)) AND ((f.profile_id = ?) OR (f.friend_id = ?))',array($userProfileId, $userProfileId, $acceptProfileId, $acceptProfileId))
            ->select('count(*) as count');    
       }
       else
       {
            $q = Doctrine::getTable('arFriend')
             ->createQuery('f')
            ->where('((f.profile_id = ?) OR (f.friend_id = ?)) AND ((f.profile_id = ?) OR (f.friend_id = ?))',array($userProfileId, $userProfileId, $acceptProfileId, $acceptProfileId))
            ->select('count(*) as count'); 
       }
       
      

       return ($q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR) > 0);
    }
    
     
}