<?php

/**
 * PluginarDropFilePreview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginarDropFilePreview extends BasearDropFilePreview
{
    
    const PERSISTENCE_SMALL = "small";
    const PERSISTENCE_MED = "med";
    const PERSISTENCE_BIG = "big";
    
    /**
     * devuelve una parte del archivo
     * 
     * @param <int $pos>
     * @return <arDropFileChunk>
     */
    public function getChunk($pos)
    {
       return Doctrine_Core::getTable('arDropFileChunkPreview')
               ->getByDropIdAndPos($this->getId(), $pos);
    }
    
    public function getChunks()
    {
       return Doctrine_Core::getTable('arDropFileChunkPreview')
               ->getByDropId($this->getId());
    }
    
    
    
    public function countChunks()
    {
       
       return Doctrine_Core::getTable('arDropFileChunkPreview')
               ->countById($this->getId());
    }
    
    public function getDropFile()
    {
        return Doctrine_Core::getTable('arDropFile')
               ->getById($this->getDropFileId());
    }

}