<?php

/**
 * PluginarTagEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarTagEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarTagEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarTagEnc');
    }
    
    /**
    * 
    * @param int $tagId:
    * @param int $userId:
    * 
    * @return arTagEnc
    */
    public function retrieveContentById($tagId, $userId )
    {
        $query = Doctrine_Core::getTable('arTagEnc')
            ->createQuery('u')
            ->andWhere('u.tag_id = ?', $tagId)
            ->andWhere('u.user_id = ?', $userId);

        return $query->fetchOne();
    }
}