<?php

/**
 * PluginarWallCommentEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallCommentEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallCommentEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallCommentEnc');
    }
    
  /**
  * 
  * @param int $messageId:
  * @param int $userId:
  * 
  * @return arWallEncContent
  */
  public function retrieveContentById($commentId, $userId )
  {
    $query = Doctrine_Core::getTable('arWallCommentEnc')
            ->createQuery('u')
            ->andWhere('u.wall_comment_id  = ?', $commentId)
            ->andWhere('u.user_id = ?', $userId);

    return $query->fetchOne();
  }
}