<?php

/**
 * PluginarProfileUploadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarProfileUploadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarProfileUploadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarProfileUpload');
    }
    
  /**
   * 
   * Devuelve el objeto arProfileUpload con la imagen
   * principal del usuario si la tiene
   * 
   *
   * @param  <int $user_id> the user_id
   *
   * @return <arProfileUpload>
   */
  public function retrieveByUserId($user_id)
  {
    $query = Doctrine_Core::getTable('arProfileUpload')->createQuery('u')
      ->where('u.user_id = ?', $user_id)
      ->addWhere('u.is_profile = ?', true);

    return $query->fetchOne();
  }
  
  /**
    * devuelve un registro por el nombre
    * 
    * @param <$id>
    * @return <arWallUpload>
    */
  public function retrieveByName($name)
  {
    $query = Doctrine_Core::getTable('arProfileUpload')
            ->createQuery('u')
            ->where('u.file_name = ?', $name);

    return $query->fetchOne();
  }
}