<?php

/**
 * PluginarWallMessageHasProfileListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallMessageHasProfileListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallMessageHasProfileListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallMessageHasProfileList');
    }
}