<?php

/**
 * PluginarWallUpload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    Arquematics
 * @subpackage model
 * @author     Javier Trigueros Martinez de los Huertos javiertrigueros@arquematics.com
 * @version    0.1
 */
abstract class PluginarWallUpload extends BasearWallUpload
                                    implements iFileResource
{
    public static $mimeArr =  array(
        'image/gif',
        'image/jpeg',
        'imagen/png',
        'image/tiff',
        'image/x-portable-bitmap');
    
    
    public static $d3ExtensionArr =  array(
        'obj',
        'stl');
    /**
     * es un link valido
     * 
     * @return boolean
     */
    /*
    public function hasValid()
    {
        return true;   
    }*/
    
    
    
    public function isImageFile()
    {
        return in_array($this->getMimeContentType(), arWallUpload::$mimeArr);
    }
    
    public function is3dFile()
    {
        
        $ret = ($this->getMimeContentType() == 'text/plain')
               || ($this->getMimeContentType() == 'application/octet-stream');
        return ($ret && in_array($this->getExtension(), arWallUpload::$d3ExtensionArr));
    }
    
    public function getPathAndFile($size = 'original')
    {
         return sfConfig::get('app_aToolkit_writable_dir').DIRECTORY_SEPARATOR.'arWallUpload'.DIRECTORY_SEPARATOR.$size.DIRECTORY_SEPARATOR.$this->getFileName();
    }
    
    public function getBaseName()
    {
        $filenameitems = explode(".", $this->getFileName());
        return $filenameitems[0];
    }
    
    public function getExtension()
    {
        $filenameitems = explode(".", $this->getFileName());
        return $filenameitems[count($filenameitems) - 1];
    }

}