<?php

/**
 * PluginarWallLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallLink');
    }


    public static function getMessageLinks($messageId, $profileId = false, $conn = false)
    {
        
         $q = Doctrine::getTable('arWallLink')->createQuery('l')
            ->where('l.wall_message_id = ?',$messageId);
         
         if ($profileId && sfConfig::get('app_arquematics_encrypt', false))
         {
             
           $q->leftJoin('l.EncContent ec ON (l.id = ec.wall_link_id AND ec.user_id = ?)',$profileId)
              ->andWhere('ec.user_id = ?',$profileId);
         }
         
         if ($conn)
         {
           $q->setConnection($conn);  
         }

         return $q->execute();
    }


    /**
     * devuelve los recursos por array de ids
     *
     * @param <array $ids> 
     * @param [int $profileId] opcional. $profileId no se usa al guardar en menssage->save
     * 
     * @return <array of arWallLink>
     */
    public static function getByIds($ids, $profileId = false)
    {

        $q = Doctrine_Query::create()
            ->from('arWallLink l')
            ->whereIn('l.id',$ids);
        
        if ($profileId && sfConfig::get('app_arquematics_encrypt', false))
        {
             
           $q->leftJoin('l.EncContent ec ON (l.id = ec.wall_link_id AND ec.user_id = ?)',$profileId)
              ->andWhere('ec.user_id = ?',$profileId);
        }
        

        return $q->execute();
    }


    
    /**
    * devuelve un registro por la id
    * 
    * @param <$id>
    * @return <arWallLink>
    */
    public function retrieveById($id)
    {
        $query = Doctrine_Core::getTable('arWallLink')->createQuery('u')
        ->where('u.id = ?', $id);

        return $query->fetchOne();
    }
    
    /**
    * devuelve un registro por el nombre
    * 
    * @param <$id>
    * @return <arWallUpload>
    */
  public function retrieveByName($name)
  {
    $query = Doctrine_Core::getTable('arWallLink')
            ->createQuery('u')
            ->where('u.file_name = ?', $name);

    return $query->fetchOne();
  }
}