<?php

/**
 * PluginarWallImageUploadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarWallImageUploadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarWallImageUploadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarWallImageUpload');
    }
    
    /**
     * devuelve los registros de las  imagenes  por ids
     *
     * @param <array $ids> 
     * 
     * @return <array>
     */
    public static function getByIds($ids)
    {

        $q = Doctrine_Query::create()
            ->from('arWallImageUploads d')
            ->whereIn('d.id',$ids);
        
        return $q->execute();
    }
}