<?php

/**
 * PluginarPhotoGallerySlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarPhotoGallerySlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarPhotoGallerySlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarPhotoGallerySlot');
    }
}