<?php

/**
 * PluginaBlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginaBlogPost extends BaseaBlogPost
{
  public $engine = 'aBlog';
    
  public function getVirtualPageSlug()
  {
   //return url_for('@ar_blog_post_edit?id='.$this->getId());
   //return '@ar_blog_post_edit?page_back=wall&id='.$this->getId();
   //return url_for('@a_blog_show_post_id?id='.$this->getId());
      
   //return url_for('@a_blog_show_post_id?id='.$this->getId());
   //return '@a_blog_show_post?slug='.$this->getSlug();
   return '@a_blog_show_post_id?id='.$this->getId();
   
  }
}
