<?php

/**
 * PluginarCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarComment');
    }
    /**
     * comentarios hijos de $parentId
     * 
     * @param <int $parentId>
     * @return <array of arComment>
     */
    public static function getChildren($parentId)
    {
         return Doctrine::getTable('arComment')->createQuery()
                ->andWhere('parent = ?', $parentId)
                ->andWhere('comment_approved = ?', true)
                ->execute();
    }

    public static function getByBlogItemId($id, $parenId = false)
    {
         $q = Doctrine::getTable('arComment')->createQuery()
                ->andWhere('a_blog_item_id = ?', $id)
                ->andWhere('comment_approved = ?', true);
         
         if (!$parenId)
         {
             $q->andWhere('parent is NULL');  
         }
         else 
         {
             $q->andWhere('parent = ?', $parenId);
         }
                
         return $q->execute();
    }
    
    public static function getAllByBlogItemId($id)
    {
         $q = Doctrine::getTable('arComment')->createQuery()
                ->andWhere('a_blog_item_id = ?', $id)
                ->andWhere('comment_approved = ?', true);
          
         return $q->execute();
    }
    
    /**
     * cuenta los comentarios
     * 
     * @param <a_blog_item_id $id>
     * @return <int>
     */
    public static function countByBlogItemId($id)
    {
         $q = Doctrine::getTable('arComment')->createQuery()
                ->andWhere('a_blog_item_id = ?', $id)
                ->andWhere('comment_approved = ?', true)
                ->select('COUNT(id)');
         
         return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    /**
     * cuenta el número de comentarios pendientes de moderación
     * 
     * @return <int>
     */
    public static function countNotModerated()
    {
         $q = Doctrine::getTable('arComment')->createQuery()
                ->andWhere('comment_approved = ?', false)
                ->select('COUNT(id)');
         
         return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    
    /**
     * Query con todos los comentarios
     * 
     * @return <Query>
     */
    public static function getQueryAll()
    {
         return  Doctrine::getTable('arComment')
                 ->createQuery();
               
    }
    
    public static function getQueryApprovedAll()
    {
        
         $query = Doctrine_Core::getTable('arComment')
                ->createQuery('a')
                ->leftJoin('a.User u');
         
         return $query;
               
    }
    
    
}