<?php

/**
 * PluginarExcerptEncTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginarExcerptEncTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginarExcerptEncTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginarExcerptEnc');
    }
    
     /**
    * 
    * @param int $messageId:
    * @param int $userId:
    * 
    * @return arBlogExcerptEnc
    */
    public function retrieveExcerptById($itemId, $userId )
    {
        $query = Doctrine_Core::getTable('arExcerptEnc')
            ->createQuery('u')
            ->andWhere('u.a_blog_item_id = ?', $itemId)
            ->andWhere('u.user_id = ?', $userId)
            ->orderBy('u.created_at DESC');

        return $query->fetchOne();
    }
}